### ISSUE TITLE
No build folder when installing version 3.0.5

### ISSUE THREAD

**Issue by OlekVano** [prasanaworld/puppeteer-screen-recorder#113]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

After having run `npm i puppeteer-screen-recorder` I see that there is no build folder. 
Same happens when I run `npm i puppeteer-screen-recorder@3.0.5`.
![image](https://github.com/user-attachments/assets/f367d630-91b6-4449-a64e-18007da905e6)

When I run `npm i puppeteer-screen-recorder@3.0.3` the build folder is there.
![image](https://github.com/user-attachments/assets/1518bb1e-ec3b-490f-b9b9-662bf80a8976)

- **Steps to reproduce**
1. Create a folder
2. Open folder in cmd or vscode
3. Run npm init
4. Press enter lots of times
5. Run `npm i puppeteer-screen-recorder@3.0.5`

**Comment by prasanaworld** [comment]
## Details about Broken v3.0.5 Release
I want to start by apologizing for the broken v3.0.5 release of Puppeteer Screen Recorder. I understand the frustration and inconvenience this has caused, and I'm truly sorry for the mistake.

### Issue root cause
During the upgrade of dev dependencies, I attempted to run the automated build to deploy the package to npm using GitHub Actions and my cloud setup. Unfortunately, the build process failed to generate the correct build, and my script deployed a partial build to the npm registry without the actual files. This resulted in a broken v3.0.5 release.

I take full responsibility for the mistake. I was busy with personal work at the time and didn't prioritize fixing the issue as quickly as I should have. I also failed to properly validate the build before deploying it, which was a critical error.

### Learned and What's Next
Please be assured that I've taken steps to prevent this from happening again in the future. I've reviewed and updated the build script to include additional validation checks, and I'll make sure to prioritize testing and validation before deploying any future releases.

### Special Thanks
I'd like to extend a huge thank you to @OlekVano for bringing this issue to my attention and helping to prioritize its resolution. Once again, I apologize for the inconvenience this has caused, and I appreciate your understanding. Thank you for your continued support of Puppeteer Screen Recorder.

### Fix
The issue has been fixed, and a new release ([v3.0.6](https://github.com/prasanaworld/puppeteer-screen-recorder/releases/tag/v3.0.6)) has been deployed with the correct build. You can upgrade to the latest version by running `npm install puppeteer-screen-recorder@latest` or `yarn add puppeteer-screen-recorder@latest`.
