### ISSUE TITLE
Support for transparent video background. (Different File formats)

### ISSUE THREAD

**Issue by ariel-frischer** [prasanaworld/puppeteer-screen-recorder#13]
- **I'm submitting a ...**
  [x] feature request
  [x] question about how to use this project

- I would really like to use this to create a video with a transparent background but mp4 does not support alpha channel, I would need to convert it to `webm` or `mov` formats which support alpha channels. Does this library support that? Can it be added?

**Comment by prasanaworld** [comment]
[To support different file format](https://github.com/prasanaworld/puppeteer-screen-recorder/issues/9)

**Comment by prasanaworld** [comment]
Added Support for file format mp4, webm, mov and avi. 

https://github.com/prasanaworld/puppeteer-screen-recorder/tree/v2.0.1

**Comment by ariel-frischer** [comment]
@prasanaworld is there any documentation on how to render now with new transparent background??

**Comment by wedios** [comment]
Please share an example of record video with transparent background, webm and mov are supported but not showing transparent  background. thanks in advance.

**Comment by bladerik** [comment]
I was able to produce .mov video with transparent background. Great news is you just have to tweak some options. 

 Now to the code example:

```
const puppeteer = require('puppeteer');
const { PuppeteerScreenRecorder } = require('puppeteer-screen-recorder');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  const recorderOptions = {
    "format": "png",
    "videoCodec": "png", 
    "videoPixelFormat": "rgba",
    "fps": 60
  }
  const recorder = new PuppeteerScreenRecorder(page, recorderOptions);
  const testHtml = "<!DOCTYPE html>\n<html>\n<head>\n<title>\n</title>\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n<style>\n    body {margin: 0}\n    h1{font-family:Arial, sans-serif;color:red;margin: 0; text-transform: uppercase;}\n    .container {\n        width: 1080px;\n        height: 1080px;\n        text-align: center;\n        padding-top: 100px;\n    }\n</style>\n</head>\n<body>\n<h1>headline</h1>\n</body>\n</html>";
  await page.setContent(testHtml);

  // set transparent background in browsers
  const client = await page.target().createCDPSession();
  await client.send("Emulation.setDefaultBackgroundColorOverride", {
      color: { r: 0, g: 0, b: 0, a: 0 },
  });

  await recorder.start('./report/video/simple.mov'); // supports extension - mp4, avi, webm and mov
  await page.waitForTimeout(5000);
  await recorder.stop();
  await browser.close();
})();
```

The drawback is you need to use .png format, which produced non-smooth animation as I use the recorder via AWS lambda. If you can somehow use gpu or have access to performant dedicated server, you probably will be able to achieve 60 fps.

Basically you need to:
- use .mov as .mp4 container do not support transparent background
- use png as format instead of default jpeg
- use pixel format and codec that support transparency
- send Emulation.setDefaultBackgroundColorOverride to override the default background color to transparent, beware: css can overwrite this 

Also you will have to open the video in VLC or other video editor as chances are the codec is not supported in standard video players or browser. The background is shown as black in VLC but the background is transparent - you can verify this with ffprobe or use ffmpeg to slice the video into transparent png images.

For comparison, I'm also attaching 3 examples:
 - first example is working video animation with transparent background,
 - second video is without transparency, but uses the png format to show that this causes the animation to lag,
 - third video uses default settings, so it is not transparent and it use jpeg format 

https://user-images.githubusercontent.com/1346249/212538834-da43e2cb-d161-4a46-9235-f98bc70db32a.mov

https://user-images.githubusercontent.com/1346249/212538842-d36c2650-6bb0-4090-977d-b8d9b6d9b0e0.mov

https://user-images.githubusercontent.com/1346249/212538845-98a89845-75ce-40d6-84b2-e2429ed10875.mov

**Comment by wesbos** [comment]
@bladerik thanks so much for this. Can I ask where you then use these files? Are you overlaying them on top of other video? In the browser? I can't seem to find a video editor that will play them.
