### ISSUE TITLE
Video Recording Speed

### ISSUE THREAD

**Issue by elbadryd** [prasanaworld/puppeteer-screen-recorder#26]
- **I'm submitting a ...**
  [ X] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- Hello,
I am trying to use this package to record html animations but it seems that the output mp4 is faster than the actual animation i am capturing? Am i doing something wrong? or is there a way to slow down the speed of capture?

```await page.goto('https://webkit.org/blog-files/3d-transforms/morphing-cubes.html');
    await page.waitForSelector('#shape');
    await recorder.start(clipPath);
    setTimeout(async () => {
      console.log('stopping recording');
      await recorder.stop();
      console.log('closing page');
      await page.close();
      console.log('closed page');
    }, 12000);
```

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
- Output: https://user-images.githubusercontent.com/40278300/151414812-027dcbdd-0662-4979-af85-4ab518fd8d75.mp4
Original: https://webkit.org/blog-files/3d-transforms/morphing-cubes.html

**Comment by elbadryd** [comment]
@prasanaworld can you please link the duplicate issue

**Comment by SerGem811** [comment]
+1, can you show me the duplicated link?

**Comment by OutLawzDub** [comment]
+1, need the duplicated link

**Comment by sanschaise** [comment]
+1

**Comment by prasanaworld** [comment]
Sorry for my delayed response. I was busy with some personal work. 

The recording speed of the video is based on the frame rate provided by [Page.startScreencast dev tool protocol API](https://github.com/prasanaworld/puppeteer-screen-recorder/blob/main/src/lib/pageVideoStreamCollector.ts#L59)

I would recommend changing the [FPS value](https://prasanaworld.github.io/puppeteer-screen-recorder/globals.html#puppeteerscreenrecorderoptions) to slow down.  
Doc: https://prasanaworld.github.io/puppeteer-screen-recorder/globals.html#puppeteerscreenrecorderoptions

However, the problem may still persist because of the bug in the [puppeteer core API](https://github.com/prasanaworld/puppeteer-screen-recorder/issues/6#issuecomment-842558748) 

closing the issue in favor of the duplicate https://github.com/prasanaworld/puppeteer-screen-recorder/issues/23
